n1 = float(input("Informe o primeiro número decimal:"))
n2 = float(input("Informe o segundo número decimal:"))
n3 = abs(n1) - abs(n2)
n3 = round(n3,2)
print(f"A diferença absoluta entre os números é:{n3}")